// components/organisms/Footer.vue
<template>
  <footer class="footer p-10 grid grid-cols-12 grid-rows-2 place-items-center">
    <Logo size="small" class="col-span-full md:place-self-start md:row-start-1"/>
    <div class="footer__contact col-span-full mt-5 flex flex-col text-center md:place-self-end md:row-start-1 md:mt-0">
      <span class="footer__contact__title font-bold mb-3">Contato</span>
      <a href="mailto:perifacode@gmail.com">perifacode@gmail.com</a>
    </div>
    <div class="footer__social col-span-full mt-5 flex md:place-self-end md:row-start-2 md:mr-2 md:mt-0">
      <SocialListHorizontal class="gap-5"/>
    </div>
    <Divider class="col-span-full mt-10 mb-5 md:hidden"/>
    <div class="footer__copyright col-span-full mt-5 flex flex-col text-center md:text-left md:place-self-start md:row-start-2 md:mt-0 md:self-end">
      <div class="terms flex">
        <NuxtLink to="/manifesto" class="mb-2 uppercase">Manifesto</NuxtLink>
        <NuxtLink to="/coc" class="mb-2 uppercase">Código de Conduta</NuxtLink>
      </div>
      <div class="copyright flex flex-col md:flex-row mt-3">
        <span class="mb-3 md:mr-2 md:mb-0">&copy; perifaCode 2021.</span>
        <span>Todos os direitos reservados.</span>
      </div>
    </div>
  </footer>
</template>

<script lang="ts">
  import Vue from 'vue'

  export default Vue.extend({

  })
</script>

<style lang="scss" scoped>
.footer {
  color: color('text', 'primaryLight');
  background-color: color('bg', 'secondaryDark');
  width: 100%;
  .footer__contact {
    span, a {
      font-family: $secondary-font;
    }
  }
  .footer__copyright {
    font-family: $primary-font;
    a {
      color: color('brand', 'base');
      margin-right: 1.5rem;
    }
  }
}
</style>

// src/components/Footer.tsx
import { Box, Flex, Stack, Text } from "@chakra-ui/react"
import Link from "next/link"
import { RiGithubFill, RiInstagramFill, RiTwitterFill, RiYoutubeFill } from "react-icons/ri"
import { IconLink } from "./IconLink"
import { Logo } from "./Logo"

export const Footer = () => {
  return (
    <Flex
      as="footer"
      bg="blackAlpha.900"
      color="white"
      py="2rem"
      px="5rem"
      justify="space-between"
      direction={["column", "row"]}
      align="center"
    >
      <Flex direction="column" rowGap={4} align={["center", "flex-start"]}>
        <Box>
          <Logo />
        </Box>
        <Text as="span" textAlign={["center", "left"]}>© perifaCode 2022. Todos os direitos Reservados.</Text>
        <Stack my="1rem" textTransform="uppercase" textAlign={["center", "left"]}>
          <Link href="/manifesto"> Manifesto </Link>
          <Link href="/coc"> Código de Conduta </Link>
        </Stack>
      </Flex>
      <Flex direction="column" rowGap={2} textAlign="center" py="1rem">
          <Text as="span">Contato</Text>
          <Link href="mailto:contato@perifacode.com">contato@perifacode.com</Link>
          <Flex gap="1rem">
            <IconLink 
              href="https://www.youtube.com/perifacode/" 
              icon={RiYoutubeFill} 
            />
            <IconLink 
              href="https://www.twitter.com/perifacode/" 
              icon={RiTwitterFill} 
            />
            <IconLink 
              href="https://www.instagram.com/perifacode/" 
              icon={RiInstagramFill} 
            />
            <IconLink 
              href="https://www.github.com/perifacode/" 
              icon={RiGithubFill} 
            />
          </Flex>
      </Flex>
    </Flex>
  )
}
